name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Makefile inside Dev Container
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            make install
            make lint
            make test
            make format
